"""add_tickets

Revision ID: 817ffe1167a1
Revises: 9fe7fa1dc192
Create Date: 2020-10-25 00:00:46.980398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "817ffe1167a1"
down_revision = "9fe7fa1dc192"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Unicode(length=50), nullable=False),
        sa.Column("description", sa.Unicode(length=255), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    # ### end Alembic commands ###
